/** Icons that admins can assign to explorer items and skills. */
export const ICON_GROUPS = {
  file: [
    ["markdown", "Markdown"],
    ["typescript", "TypeScript dosyası"],
    ["json", "JSON"],
    ["file", "Dosya"],
    ["code", "Kod"],
    ["pdf", "PDF"],
    ["image", "Görsel"],
    ["play", "Oynat"],
    ["link", "Bağlantı"],
    ["globe", "Web"],
    ["github", "GitHub"],
    ["medium", "Medium"],
    ["linkedin", "LinkedIn"],
    ["email", "E-posta"],
  ],
  folder: [
    ["folder", "Klasör"],
    ["person", "Kişi"],
    ["rocket", "Roket"],
    ["book", "Kitap"],
    ["certificate", "Sertifika"],
    ["mail", "Posta"],
    ["briefcase", "Çanta"],
    ["tools", "Araçlar"],
    ["beaker", "Deney"],
    ["camera", "Kamera"],
    ["game", "Oyun"],
    ["cloud", "Bulut"],
    ["database", "Veritabanı"],
    ["server", "Sunucu"],
    ["layers", "Katmanlar"],
    ["lightbulb", "Fikir"],
    ["megaphone", "Duyuru"],
    ["note", "Not"],
    ["organization", "Topluluk"],
    ["project", "Proje"],
    ["star", "Yıldız"],
    ["heart", "Kalp"],
    ["calendar", "Takvim"],
    ["comment", "Yorum"],
    ["home", "Ev"],
    ["shield", "Kalkan"],
    ["tag", "Etiket"],
    ["target", "Hedef"],
    ["terminal", "Terminal"],
    ["verified", "Onaylı"],
    ["wand", "Sihirli değnek"],
  ],
  tech: [
    ["ultralytics", "Ultralytics"],
    ["mediapipe", "MediaPipe"],
    ["opencv", "OpenCV"],
    ["tensorflow", "TensorFlow"],
    ["pytorch", "PyTorch"],
    ["scikitlearn", "Scikit-learn"],
    ["keras", "Keras"],
    ["numpy", "NumPy"],
    ["pandas", "Pandas"],
    ["jupyter", "Jupyter"],
    ["huggingface", "Hugging Face"],
    ["langchain", "LangChain"],
    ["ollama", "Ollama"],
    ["openai", "OpenAI"],
    ["anthropic", "Anthropic"],
    ["claude", "Claude"],
    ["gemini", "Gemini"],
    ["cursor", "Cursor"],
    ["huawei", "Huawei"],
    ["googlecloud", "Google Cloud"],
    ["aws", "AWS"],
    ["cloudflare", "Cloudflare"],
    ["vercel", "Vercel"],
    ["netlify", "Netlify"],
    ["supabase", "Supabase"],
    ["firebase", "Firebase"],
    ["nextjs", "Next.js"],
    ["react", "React"],
    ["vue", "Vue"],
    ["nuxt", "Nuxt"],
    ["angular", "Angular"],
    ["svelte", "Svelte"],
    ["flutter", "Flutter"],
    ["dart", "Dart"],
    ["kotlin", "Kotlin"],
    ["android", "Android"],
    ["swift", "Swift"],
    ["apple", "Apple"],
    ["html", "HTML5"],
    ["css", "CSS"],
    ["tailwind", "Tailwind CSS"],
    ["javascript", "JavaScript"],
    ["typescriptlang", "TypeScript"],
    ["threejs", "Three.js"],
    ["webgl", "WebGL"],
    ["vite", "Vite"],
    ["webpack", "Webpack"],
    ["redux", "Redux"],
    ["python", "Python"],
    ["fastapi", "FastAPI"],
    ["django", "Django"],
    ["flask", "Flask"],
    ["nodejs", "Node.js"],
    ["express", "Express"],
    ["dotnet", ".NET"],
    ["spring", "Spring"],
    ["go", "Go"],
    ["rust", "Rust"],
    ["cplusplus", "C++"],
    ["graphql", "GraphQL"],
    ["prisma", "Prisma"],
    ["postgresql", "PostgreSQL"],
    ["mysql", "MySQL"],
    ["mssql", "MSSQL"],
    ["sqlite", "SQLite"],
    ["mongodb", "MongoDB"],
    ["redis", "Redis"],
    ["elasticsearch", "Elasticsearch"],
    ["rabbitmq", "RabbitMQ"],
    ["kafka", "Kafka"],
    ["docker", "Docker"],
    ["kubernetes", "Kubernetes"],
    ["terraform", "Terraform"],
    ["ansible", "Ansible"],
    ["jenkins", "Jenkins"],
    ["githubactions", "GitHub Actions"],
    ["nginx", "Nginx"],
    ["linux", "Linux"],
    ["git", "Git"],
    ["gitlab", "GitLab"],
    ["bitbucket", "Bitbucket"],
    ["vscode", "VS Code"],
    ["figma", "Figma"],
    ["blender", "Blender"],
    ["unity", "Unity"],
    ["arduino", "Arduino"],
    ["raspberrypi", "Raspberry Pi"],
    ["selenium", "Selenium"],
    ["jest", "Jest"],
    ["cypress", "Cypress"],
    ["storybook", "Storybook"],
    ["postman", "Postman"],
    ["notion", "Notion"],
    ["slack", "Slack"],
    ["trello", "Trello"],
    ["jira", "Jira"],
  ],
} as const;

type Group = (typeof ICON_GROUPS)[keyof typeof ICON_GROUPS];
export type IconKey = Group[number][0];

export const ICON_KEYS: IconKey[] = Object.values(ICON_GROUPS).flatMap((g) => g.map(([k]) => k));

export const ICON_LABELS: Record<IconKey, string> = Object.fromEntries(
  Object.values(ICON_GROUPS).flatMap((g) => g.map(([k, l]) => [k, l])),
) as Record<IconKey, string>;

export function isIconKey(value: unknown): value is IconKey {
  return typeof value === "string" && (ICON_KEYS as string[]).includes(value);
}
