-- Generated by scripts/generate-cms-seed.mjs from supabase/content/cms.json.
-- Initial content only: ON CONFLICT DO NOTHING keeps later admin edits intact.
begin;

insert into public.site_settings (id, name, title_tr, title_en, subtitle_tr, subtitle_en, location_tr, location_en, email, github_url, linkedin_url, medium_url, website_url, avatar_url, available_for_work, current_focus_tr, current_focus_en, education_degree_tr, education_degree_en, education_school, education_years, education_gpa, seo_title, seo_description_tr, seo_description_en, chat_greeting_tr, chat_greeting_en, terminal_whoami) values (1, 'Osman Buğra BOLAT', '', 'AI powered AI & Cloud Engineer', '', 'Like every engineer should, I solve problems.', 'Türkiye', 'Turkey', 'contact@bugrabolat.dev', 'https://github.com/osmanbugrabolat', 'https://linkedin.com/in/osmanbugrabolat', 'https://medium.com/@osmanbugrabolat', 'https://bugrabolat.dev', '/bugra.png', false, array[]::text[], array['Building scalable Web & Mobil applications', 'Exploring AI/ML integrations']::text[], '', 'Computer Engineering', 'University', '2020 – 2024', '3.4 / 4.0', 'Osman Buğra BOLAT', '', 'Portfolio of Buğra Bolat — Full Stack Developer specializing in Next.js, TypeScript, and modern web technologies.', 'Merhaba! Ben BuğrAI. Osman Buğra''nın portfolyosu hakkında merak ettiğiniz her şeyi sorabilirsiniz.', 'Hi! I''m BuğrAI. Ask me anything about Osman Buğra''s portfolio.', 'Osman Buğra BOLAT - AI powered AI & Cloud Engineer') on conflict (id) do nothing;

insert into public.explorer_nodes (id, parent_id, kind, name, sort_order, icon, show_in_explorer) values ('39187750-6cde-592d-b967-a018a7487af5', null, 'folder', 'about-me', 0, 'person', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('2979537e-ca14-5116-95ef-df81892e6a63', '39187750-6cde-592d-b967-a018a7487af5', 'file', 'WhoAmI.md', null, 'home', 0, '/', null, null, '', '{{profile-header}}

## About Me

As a computer engineering graduate ranking 3rd in the Faculty of Technology and 2nd in my department at Selçuk University (graduated in 2026 with a 3.75 GPA), I have aligned my technical focus on integrating Computer Vision and Deep Learning models into cloud infrastructures throughout my studies, and I continue to advance my expertise in these fields.

During my undergraduate years, I gained hands-on experience in the automation and deployment of AI-based operational processes based on Docker, CI/CD pipelines, DevOps, and MLOps principles.

I combine this strong academic foundation with leadership and communication skills developed through technology community leadership and project management roles. I am a dynamic engineer who quickly adapts to the operational requirements of complex projects, takes responsibility in technical processes, and thrives in collaborative team environments.

## Current Focus

{{current-focus}}

## Tech Stack & Ecosystem

A high-level overview of the technologies I use to bring ideas to life:

{{tech-stack}}', 'markdown', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, sort_order, icon, show_in_explorer) values ('12ec0a70-b90b-5dcd-9e16-5b9704ec4275', null, 'folder', 'projects', 1, 'rocket', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, sort_order, icon, show_in_explorer) values ('704f64e6-d5c5-58f9-9efe-2024daccc86b', '12ec0a70-b90b-5dcd-9e16-5b9704ec4275', 'folder', 'pong-with-mediapipe', 0, null, true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('37de67c3-5f8d-5c3e-9bca-4e637ee2bdce', '704f64e6-d5c5-58f9-9efe-2024daccc86b', 'file', 'README.md', null, 'markdown', 0, '/projects/pong-with-mediapipe', null, null, '# Neon Pong AI: Hand-Tracking Web Game

**Canlı Demo:** [Buraya tıklayarak oyunu hemen tarayıcınızda oynayabilirsiniz!](https://osmanbugrabolat.github.io/pong-with-mediapipe/)

**Neon Pong AI**, Google''s Mediapipe el takibi teknolojisini kullanan, fütüristik neon tasarıma sahip modern bir web tabanlı Pong oyunudur. Oyunu klavye veya fare ile değil, doğrudan **el hareketlerinizle** web kamerası üzerinden oynarsınız!

![Oyun İçi Görüntü](https://raw.githubusercontent.com/osmanbugrabolat/pong-with-mediapipe/main/game.png)

## Özellikler

- **Yapay Zeka Destekli El Takibi:** Google Mediapipe sayesinde avuç içiniz anlık olarak tespit edilir ve raketiniz elinizle senkronize hareket eder.
- **Kamera Mini-Ekranı:** Oyun başladıktan sonra ekranın sağ alt köşesinde beliren kamera penceresi ile kendi hareketlerinizi ve tespit edilen el noktalarını anlık olarak takip edebilirsiniz.
- **Retro Ses Efektleri:** Web Audio API kullanılarak üretilen çarpma ve skor sesleriyle nostaljik atari deneyimini yaşayın. İstenirse menü üzerinden sesler tamamen kapatılabilir.
- **Takım Seçimi & Akıllı Yönlendirme:** Başlangıçta oynamak istediğiniz takımı (Sol/Sağ) seçebilirsiniz. Seçiminize göre kamera ayna etkisini hesaba katarak doğru elinizi algılar. AI rakip ise otomatik olarak karşı tarafa geçer.
- **Neon / Cyberpunk Tasarım:** Tamamen Vanilla CSS ile tasarlanmış cam efektli, karanlık temalı ve yüksek kaliteli parlamalara sahip interaktif oyun menüsü.
- **Akıllı Rakip:** Topu takip eden ancak insanımsı bir hata payı barındıran bir yapay zeka. Ralliler uzadıkça heyecan artar, top hızlanır!
- **Tam Kontrol:** Oyun başlamadan önce menü üzerinden topun başlangıç hızını ayarlayabilirsiniz.

## Kullanılan Teknolojiler

- **HTML5 & CSS3:** Modern, duyarlı ve şık arayüz tasarımı.
- **Vanilla JavaScript (ES6+):** Oyun döngüsü, çarpışma fizikleri ve uygulama mantığı.
- **Web Audio API:** Performans dostu, dosya indirme gerektirmeyen tarayıcı tabanlı retro ses sentezleme.
- **HTML5 Canvas:** Kesintisiz oyun çizimi, animasyonlar ve neon parlama efektleri.
- **[Google Mediapipe](https://developers.google.com/mediapipe):** Kamera üzerinden anlık görüntü işleme ve iskelet tabanlı el takibi (Hand Tracking modeli).

## Nasıl Çalıştırılır?

Modern web tarayıcıları, güvenlik politikaları (CORS & Secure Context) gereği web kamerasına erişim için yerel bir sunucu bağlantısı gerektirir. Bu yüzden HTML dosyasına çift tıklamak yerine yerel sunucu kullanmalısınız.

1. Bilgisayarınızda [Node.js](https://nodejs.org/)''in kurulu olduğundan emin olun.
2. Projeyi bilgisayarınıza klonlayın:

    ```
    git clone https://github.com/osmanbugrabolat/pong-with-mediapipe.git
    ```

3. Klonlanan klasörün içine girin:

    ```
    cd pong-with-mediapipe
    ```

4. Yerel sunucuyu başlatmak için şu komutu çalıştırın:

    ```
    npx serve
    ```

5. Terminalde size verilen adresi (genellikle `http://localhost:3000`) tarayıcınızda açın.
6. Tarayıcınızın sağ üst veya sol üst kısmında belirecek olan **Kamera İzni**ni onaylayın.
7. Hızınızı, takımınızı seçin ve **OYUNA BAŞLA**''ya tıklayın!

## Oynanış İpuçları

- Kameranın elinizi (özellikle avuç içinizi) net görebileceği ve ortam ışığının iyi olduğu bir mesafede durun.
- Seçtiğiniz takıma uygun olan elinizi kameraya doğru tutun (Örn: Sol takım için sol eliniz).
- Elinizi yukarı-aşağı hareket ettirerek raketi kontrol edin.

* * *

**Geliştirici:** [Osman Buğra Bolat](https://osmanbugrabolat.com.tr)', '', 'markdown', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('4b55268d-02af-5e27-9aeb-4d53852a5077', '704f64e6-d5c5-58f9-9efe-2024daccc86b', 'file', 'Play', null, 'embed', 1, '/projects/pong-with-mediapipe/play', 'https://osmanbugrabolat.github.io/pong-with-mediapipe/', null, 'Neon Pong AI', '', 'play', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, sort_order, icon, show_in_explorer) values ('5d2e4182-2cf7-508f-975d-6e8fd47336db', '12ec0a70-b90b-5dcd-9e16-5b9704ec4275', 'folder', 'flying-birds-with-mediapipe', 1, null, true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('3fb734bb-6ab8-56cf-a10d-79d346358997', '5d2e4182-2cf7-508f-975d-6e8fd47336db', 'file', 'README.md', null, 'markdown', 0, '/projects/flying-birds-with-mediapipe', null, null, '# Flying Birds AI

**Canlı Demo:** [Oyunu Buradan Oynayın](https://osmanbugrabolat.github.io/flying-birds-with-mediapipe/)

![Flying Birds AI Oynanış Görüntüsü](https://raw.githubusercontent.com/osmanbugrabolat/flying-birds-with-mediapipe/main/game.png)

## Genel Bakış

Flying Birds AI, klasik engellerden kaçma oyunlarından ilham alan etkileşimli, tarayıcı tabanlı bir oyundur. Bu projeyi diğerlerinden ayıran en önemli özellik, Google''ın MediaPipe makine öğrenimi modeliyle entegre çalışmasıdır. Oyuncular bir klavye veya fare kullanmak yerine, web kameraları aracılığıyla gerçek zamanlı olarak algılanan el hareketleriyle kuşu tamamen temassız bir şekilde kontrol ederler.

Proje, "glassmorphism" tasarım prensipleri, duyarlı tuval ölçeklendirmesi, kodla üretilmiş vektörel grafikler ve Web Audio API aracılığıyla sentezlenen dinamik ses efektleri ile modern bir kullanıcı arayüzü sunmaya odaklanılarak geliştirilmiştir.

## Özellikler

- **Bilgisayarlı Görü Kontrolleri:** Kullanıcının işaret parmağını gerçek zamanlı olarak takip etmek için MediaPipe Hands modelini kullanır. Kuşun dikey konumu doğrudan kullanıcının el konumuna göre ayarlanır.
- **Responsive Tasarım:** Oyun motoru, `ResizeObserver` kullanarak tuvali, çarpışma kutularını ve oyun içi öğeleri herhangi bir bozulma olmadan her ekran boyutuna veya en boy oranına mükemmel şekilde uyacak şekilde dinamik olarak ölçeklendirir.
- **Modern Kullanıcı Arayüzü:** Şık bir glassmorphism tasarımı, açılır-kapanır ayar menüleri ve oyun alanını kapatmayan kamera önizleme ekranı içerir.
- **Yerel Sentezlenmiş Ses:** Ses efektleri, harici ses dosyalarının indirilmesine gerek kalmadan ve gecikmesiz bir deneyim sağlamak için Web Audio API kullanılarak tarayıcıda doğrudan matematiksel olarak sentezlenir.
- **Bağımsız Vektörel Grafikler:** Oyun varlıkları (örneğin kuş tasarımı), inline SVG kullanılarak matematiksel olarak oluşturulmuştur. Bu sayede yüksek çözünürlüklü ekranlarda bile sonsuz ölçeklenebilirlik ve keskin bir görüntü kalitesi sağlanır.

## Kullanılan Teknolojiler

- **HTML5 & CSS3:** Belgenin yapılandırılması ve kullanıcı arayüzünün tasarlanması için.
- **JavaScript (ES6):** Temel oyun mantığı, fizik hesaplamaları ve DOM manipülasyonu için.
- **HTML5 Canvas API:** Oyun döngüsü, borular ve grafiklerin 60 FPS hızında çizdirilmesi için.
- **MediaPipe Hands:** Tarayıcı tabanlı, gerçek zamanlı el takibi ve eklem noktası tespiti için.
- **Web Audio API:** Retro tarzı oyun ses efektlerinin sentezlenmesi için.

## Nasıl Oynanır?

1. Tarayıcınıza kameranıza erişim izni verin.
2. Elinizi, sağ alt köşedeki önizleme penceresinde görünecek şekilde kameranın önüne yerleştirin.
3. Kuşun dikey konumunu kontrol etmek için işaret parmağınızı yukarı ve aşağı doğru hareket ettirin.
4. Puanınızı artırmak için size doğru yaklaşan boruların arasındaki boşluklardan geçin.
5. Kuş borulara, tavana veya yere çarparsa oyun biter.

## Ayarlar

Oyun, başlangıç ekranında oyuncuların deneyimlerini kişiselleştirebilmesi için açılır-kapanır yapıda bir ayarlar menüsü sunar:

- **Hangi El:** Modelin kesinlikle Sağ El, Sol El veya herhangi bir eli takip etmesini seçin. Takip mantığı, web kamerasının yansımasını varsayılan olarak hesaba katar.
- **Oyun Hızı:** Yaklaşan boruların hızını ve aralarındaki dikey boşluk miktarını ayarlayın (Yavaş, Normal, Hızlı).
- **Oyun Sesi:** Web Audio API ile sentezlenen ses efektlerini açın veya kapatın.

## Yerel Cihazda Çalıştırma

Proje kameraya erişim sağladığı ve dış kaynakları (CDN) yüklediği için, HTML dosyasının doğrudan dosya yöneticisinden açılması yerine yerel bir HTTP sunucusu üzerinden çalıştırılması gerekir.

1. Depoyu yerel cihazınıza klonlayın:

    ```
    git clone https://github.com/osmanbugrabolat/flying-birds-with-mediapipe.git
    ```

2. Terminalinizde proje dizinine gidin:

    ```
    cd flying-birds-with-mediapipe
    ```

3. Yerel bir web sunucusu başlatın. Örneğin Python kullanarak:

    ```
    python3 -m http.server 8080
    ```

4. Web tarayıcınızı açın ve `http://localhost:8080` adresine gidin.

* * *

## Geliştirici

**Osman Buğra Bolat** tarafından geliştirilmiştir.
Web Sitesi: [osmanbugrabolat.com.tr](https://osmanbugrabolat.com.tr)', '', 'markdown', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('7d1203f6-c823-5cd7-bcea-9f6052333a96', '5d2e4182-2cf7-508f-975d-6e8fd47336db', 'file', 'Play', null, 'embed', 1, '/projects/flying-birds-with-mediapipe/play', 'https://osmanbugrabolat.github.io/flying-birds-with-mediapipe/', null, 'Flying Birds AI', '', 'play', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, sort_order, icon, show_in_explorer) values ('cb840721-7581-5c03-8312-dda1079428ad', '12ec0a70-b90b-5dcd-9e16-5b9704ec4275', 'folder', 'sihirli-sapan', 2, null, true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('c7ca3fc6-010b-5958-9f41-0658b8cefef4', 'cb840721-7581-5c03-8312-dda1079428ad', 'file', 'README.md', null, 'markdown', 0, '/projects/sihirli-sapan', null, null, '# Sihirli Sapan

Sihirli Sapan, Google''ın **MediaPipe** teknolojisini kullanarak yapay zeka destekli el takibi ile oynanabilen, **Matter.js** fizik motoruyla güçlendirilmiş, web tabanlı bir *Angry Birds* klonudur. Mouse veya klavyeye dokunmadan, sadece web kameranız karşısında el hareketleri yaparak kuşu sapanla fırlatıp hedefleri vurabilirsiniz!

**Canlı Demo:** [Oyunu Buradan Oynayın](https://osmanbugrabolat.github.io/sihirli-sapan/)

![Sihirli Sapan Oyun İçi Görsel](https://raw.githubusercontent.com/osmanbugrabolat/sihirli-sapan/main/game.png)

## Özellikler

- **Yapay Zeka Destekli El Takibi:** Elinizi yumruk yaparak kuşu kavrayın, geri çekin ve elinizi açarak fırlatın! (MediaPipe Hand Tracking)
- **Gelişmiş Fizik Motoru:** Matter.js kullanılarak gerçekçi yerçekimi, çarpışma ve yıkım fizikleri.
- **Dinamik Ses Efektleri:** Hiçbir harici ses dosyası kullanılmadan, tamamen *Web Audio API* ile kod üzerinden üretilen organik ses efektleri (gerilme, fırlatma, çarpışma).
- **5 Farklı Bölüm:** Her biri kendine has tasarıma (ikiz kuleler, taş kale vb.) ve hedef puana sahip 5 zorlu seviye.
- **Modern Arayüz:** Kullanıcı dostu ahşap paneller, şık butonlar ve akıcı animasyonlar (Vanilla CSS).

## Nasıl Oynanır?

1. Oyuna girdiğinizde **web kamerası izni** vermeniz gerekmektedir.
2. Ekranda elinizin iskeletini (mavi noktalar) gördüğünüzde sistem hazır demektir.
3. Elinizi sapanın üzerine getirip **yumruk (kapalı el)** yapın. Bu, kuşu kavramanızı sağlar.
4. Yumruğunuzu bozmadan elinizi geri ve aşağı doğru çekerek sapanı gerin.
5. Hedefi belirledikten sonra parmaklarınızı açarak kuşu fırlatın!
6. Blokları devirip domuzcukları patlatarak hedef puana ulaşmaya çalışın.

## Kurulum (Geliştiriciler İçin)

Proje tamamen **Vanilla JavaScript, HTML ve CSS** ile yazıldığı için herhangi bir derleme aşamasına (build step) veya sunucu tarafı bir teknolojiye ihtiyaç duymaz.

1. Repoyu bilgisayarınıza klonlayın:

    ```
    git clone https://github.com/osmanbugrabolat/sihirli-sapan.git
    ```

2. Proje dizinine gidin:

    ```
    cd sihirli-sapan
    ```

3. Dosyaları yerel bir sunucuda çalıştırın (Örn. `npx serve` veya VS Code *Live Server* eklentisi):

    ```
    npx serve .
    ```

4. Tarayıcınızda `http://localhost:3000` (veya sunucunuzun portu) adresine giderek oynamaya başlayın.

## Varlıklar (Assets) ve Teşekkürler

- **Ahşap, Cam ve Taş Bloklar:** [Kenney.nl - Physics Assets](https://kenney.nl/assets/physics-assets) üzerinden alınmıştır (Ücretsiz ve Açık Kaynak).
- **Sapan, Arkaplan ve Karakterler:** Projeye özgü olarak SVG ve PNG formatında özel üretilmiştir.
- **İkonlar:** [FontAwesome](https://fontawesome.com/) ikon kütüphanesinden faydalanılmıştır.
- **Fizik Motoru:** [Matter.js](https://brm.io/matter-js/)
- **El Takibi (AI):** [Google MediaPipe Tasks Vision](https://developers.google.com/mediapipe)

* * *

**Geliştirici:** [Osman Buğra Bolat](https://osmanbugrabolat.com.tr)', '', 'markdown', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('a2532fc2-f58a-563b-9a6c-3775078dd98b', 'cb840721-7581-5c03-8312-dda1079428ad', 'file', 'Play', null, 'embed', 1, '/projects/sihirli-sapan/play', 'https://osmanbugrabolat.github.io/sihirli-sapan/', null, 'Sihirli Sapan', '', 'play', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, sort_order, icon, show_in_explorer) values ('ac22b563-fd9a-5109-b10f-dbb7ec4e9b53', '12ec0a70-b90b-5dcd-9e16-5b9704ec4275', 'folder', 'sihirli-sapan-hsd-edition', 3, null, true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('7acf024c-d1bf-5fa8-bf1b-45d018657c9a', 'ac22b563-fd9a-5109-b10f-dbb7ec4e9b53', 'file', 'README.md', null, 'markdown', 0, '/projects/sihirli-sapan-hsd-edition', null, null, '# Sihirli Sapan - HSD Edition

Sihirli Sapan, Google''ın **MediaPipe** teknolojisini kullanarak yapay zeka destekli el takibi ile oynanabilen, **Matter.js** fizik motoruyla güçlendirilmiş, web tabanlı bir *Angry Birds* klonudur. HSD Türkiye için özel olarak geliştirilen bu versiyonda, HSD maskotunu sapanla fırlatarak yazılım böceklerini (bug) ezmeye çalışıyorsunuz!

**Canlı Demo:** [Oyunu Buradan Oynayın](https://osmanbugrabolat.github.io/sihirli-sapan-hsd-edition/)

![Sihirli Sapan HSD Edition Oyun İçi Görsel](https://raw.githubusercontent.com/osmanbugrabolat/sihirli-sapan-hsd-edition/main/game.png)

## Özellikler

- **Yapay Zeka Destekli El Takibi:** Elinizi yumruk yaparak maskotu kavrayın, geri çekin ve parmaklarınızı açarak fırlatın! Sadece web kameranız yeterli.
- **Gelişmiş Fizik Motoru:** Matter.js kullanılarak gerçekçi yerçekimi, çarpışma ve yıkım fizikleri. Ahşap, cam ve taş yapıları stratejik olarak yıkın.
- **Rekabetçi Lider Tablosu:** Oyun içi skorunuzdan harcadığınız süreye (saniye başına 30 puan ceza) bağlı olarak düşülen puanla oluşturulan adil bir "Zaman Cezası" sistemi. Günlük, Haftalık ve Aylık listelerde zirveye yerleşin!
- **10 Farklı Bölüm:** Her seviyede giderek zorlaşan hedefler, rastgele (procedural) kule üretim sistemi.
- **HSD Özel Tasarımı:** HSD Türkiye renk paleti (Sarı, Kırmızı, Lacivert, Pembe), hareketli maskot animasyonları, özel fontlar ve modern arayüz tasarımı.

## Nasıl Oynanır?

1. Oyuna girdiğinizde tarayıcınızın **kamera izni** uyarısına onay verin.
2. Ekranda elinizin iskeletini (mavi noktalar) gördüğünüzde sistem oyuna hazır demektir.
3. Adınızı girip oyuna başlayın.
4. Elinizi sapanın üzerine getirip **YUMRUK (kapalı el)** yapın.
5. Yumruğunuzu bozmadan elinizi geri ve aşağı doğru çekerek sapanı gerin.
6. Hedefi belirledikten sonra parmaklarınızı **AÇARAK** maskotu fırlatın!
7. Yapıları devirip böcekleri (bug) ezerek yüksek skor ve kısa süre yapmaya çalışın.

## Kurulum (Geliştiriciler İçin)

Proje tamamen **Vanilla JavaScript, HTML ve CSS** ile geliştirilmiştir. Herhangi bir derleme (build) işlemine gerek yoktur.

1. Repoyu bilgisayarınıza klonlayın:

    ```
    git clone https://github.com/osmanbugrabolat/sihirli-sapan-hsd-edition.git
    ```

2. Proje dizinine gidin:

    ```
    cd sihirli-sapan-hsd-edition
    ```

3. Tarayıcınızın güvenlik kuralları (CORS) gereği kameraya erişim için projeyi yerel bir sunucuda çalıştırmanız önerilir:

    ```
    npx serve .
    ```

4. Tarayıcınızda `http://localhost:3000` adresine giderek oynamaya başlayın.

## Varlıklar (Assets) ve Teknolojiler

- **Fizik Motoru:** [Matter.js](https://brm.io/matter-js/)
- **El Takibi (AI):** [Google MediaPipe Tasks Vision](https://developers.google.com/mediapipe)
- **Arayüz:** Saf (Vanilla) HTML/CSS. HSD kurumsal kimlik renkleri ve *Luckiest Guy* fontu kullanılmıştır.
- **Grafikler:** Sapan, maskot ve böcek çizimleri projeye özel SVG formatında üretilmiştir. Kule blokları ise kod ile çizilmektedir.

## Lisans

Bu proje **HSD Türkiye** için geliştirilmiş olup açık kaynak olarak paylaşılmaktadır.
*Developed by Osman Buğra Bolat for HSD Türkiye.*

* * *

**Geliştirici:** [Osman Buğra Bolat](https://osmanbugrabolat.com.tr)', '', 'markdown', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('dc512c61-493d-598b-b55e-f39b42bf22b1', 'ac22b563-fd9a-5109-b10f-dbb7ec4e9b53', 'file', 'Play', null, 'embed', 1, '/projects/sihirli-sapan-hsd-edition/play', 'https://osmanbugrabolat.github.io/sihirli-sapan-hsd-edition/', null, 'Sihirli Sapan - HSD Edition', '', 'play', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, sort_order, icon, show_in_explorer) values ('9dfcfbdb-1d56-52d2-bc7e-3ef2504c26dd', '12ec0a70-b90b-5dcd-9e16-5b9704ec4275', 'folder', 'magic-frame', 4, null, true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('1cd69a53-4f0c-5746-bde9-54ce99f0c56f', '9dfcfbdb-1d56-52d2-bc7e-3ef2504c26dd', 'file', 'README.md', null, 'markdown', 0, '/projects/magic-frame', null, null, '# Magic Frame AR

**Magic Frame**, bilgisayar kamerasını kullanarak ellerinizle oluşturduğunuz çerçeve alanına gerçek zamanlı **Yapay Zeka** ve **Artırılmış Gerçeklik (AR)** filtreleri uygulayan yenilikçi bir görüntü işleme projesidir.

Ellerinizin arasındaki boşluğu sihirli bir portala dönüştürün!

## Özellikler

- **Gerçek Zamanlı El Takibi:** Google MediaPipe altyapısı ile parmak uçlarınızı 3 boyutlu ve gecikmesiz olarak takip eder.
- **15 Farklı Sanat & Görüntü Filtresi:** Sinirsel Stil Transferi ve görüntü işleme algoritmaları ile çerçevenin içini anında bambaşka bir dünyaya dönüştürür.
- **Sihirli Ayna:** Sizi arka plandan ayırarak etrafınızı profesyonel kameralardaki gibi yoğun şekilde bulanıklaştırır.
- **Cyberpunk Neon Çerçeve:** Seçtiğiniz tarza göre rengi değişen, fütüristik görünümlü parlayan bir "HUD" çerçevesi çizer.
- **Hareket Algılama:** Efektleri değiştirmek için klavyeye dokunmanıza gerek yok. İki elinizle **çimdik atarak** filtreler arasında sihirli bir şekilde geçiş yapabilirsiniz.

## Mevcut Tarzlar (15 Filtre)

Sistem aşağıdaki 15 farklı efekti destekler:

1.  **Şeker (Candy)** - *Yapay Zeka*
2.  **Yağlı Boya (Mosaic)** - *Yapay Zeka*
3.  **Sanatsal (Udnie)** - *Yapay Zeka*
4.  **Yağmur Prensesi** - *Yapay Zeka*
5.  **Noktalıcılık (Pointilism)** - *Yapay Zeka*
6.  **Sihirli Ayna** (Arka Plan Bulanıklaştırma) - *MediaPipe*
7.  **Siyah Beyaz**
8.  **Oyun Karakteri (Cartoon)**
9.  **Kara Kalem (Siyah Beyaz)**
10.  **Kara Kalem (Renkli)**
11.  **Sulu Boya**
12.  **Sepya (Eski Fotoğraf)**
13.  **Negatif (X-Ray)**
14.  **Minecraft Piksel**
15.  **Termal Kamera (Isı Haritası)**

## Kurulum

Proje Python tabanlıdır ve çalışması için bir kaç kütüphaneye ve yapay zeka model dosyasına ihtiyaç duyar.

**1\. Gerekli kütüphaneleri yükleyin:**

```
pip install -r requirements.txt
```

**2\. Yapay Zeka modellerini indirin:**
*(Bu betik gerekli olan ONNX sanat modellerini ve MediaPipe yapay zeka modellerini tek tuşla otomatik indirecektir).*

```
python download_models.py
```

## Kullanım

Tüm kurulumları tamamladıktan sonra kameranızı açıp sihire başlamak için:

```
python main.py
```

### Kontroller

- **Filtre Değiştirmek İçin:** Her iki elinizle kameraya çerçeve yaparken, işaret parmağınızı başparmağınıza değdirip bırakın (Çimdik hareketi).
- **Çıkış Yapmak İçin:** Seçili olan pencere üzerindeyken klavyeden `q` tuşuna basın.

## Kullanılan Teknolojiler

- [OpenCV (DNN)](https://opencv.org/) - Görüntü işleme ve yapay zeka modellerini çalıştırma
- [Google MediaPipe Tasks API](https://developers.google.com/mediapipe) - El ve insan tespiti (Hand Landmarker & Image Segmenter)
- [ONNX Model Zoo](https://github.com/onnx/models) - Önceden eğitilmiş sanat modelleri

* * *

*Bu proje açık kaynaklı AI modelleri kullanılarak tasarlanmıştır.*
**Geliştirici:** [Osman Buğra Bolat](https://osmanbugrabolat.com.tr)', '', 'markdown', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('5afe51fe-e8d6-5833-8fd4-07290c4e5fdf', '9dfcfbdb-1d56-52d2-bc7e-3ef2504c26dd', 'file', 'Source Code', null, 'link', 1, null, 'https://github.com/osmanbugrabolat/magic-frame', null, '', '', 'github', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, sort_order, icon, show_in_explorer) values ('259fe09b-c0a5-5faf-8b7b-7b68465b1ad1', '12ec0a70-b90b-5dcd-9e16-5b9704ec4275', 'folder', 'kozmik-toz-enstalasyon', 5, null, true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('087940ab-ce16-547a-bf77-432a7d502003', '259fe09b-c0a5-5faf-8b7b-7b68465b1ad1', 'file', 'README.md', null, 'markdown', 0, '/projects/kozmik-toz-enstalasyon', null, null, '# Kozmik Toz Enstalasyonu

Bu proje, **MediaPipe** kullanılarak geliştirilmiş interaktif, yapay zeka destekli bir görsel ve işitsel sanat deneyimidir. Web kamerası aracılığıyla kullanıcıların el hareketlerini algılar ve bu hareketlere göre ekranda dinamik "kozmik tozlar" ile eş zamanlı sesler/müzikler üretir.

[Projeyi Deneyimle (Canlı Demo)](https://osmanbugrabolat.github.io/kozmik-toz-enstalasyon/)

## Özellikler

- **Gerçek Zamanlı El Takibi:** MediaPipe Hand Landmarker teknolojisi ile ellerin yüksek hassasiyetle izlenmesi.
- **İnteraktif Hareketler (Gestures):**
    - **Pinch (Çimdikleme):** Partiküllerin çekim kuvvetini ve yönünü kontrol eder.
    - **Fist (Yumruk):** Partikül etkileşimlerini ve ses efektlerini değiştirir.
    - **Clap (El Çırpma):** İki elin birbirine yaklaşmasıyla görsel patlamalar (burst) ve özel ses efektleri tetiklenir.
- **İki Farklı Evren (Realm):**
    - *Lydian Evreni:* Mavi, mor ve turkuaz gibi soğuk uzay tonlarına sahip varsayılan evren.
    - *Phrygian Evreni:* Kırmızı, turuncu ve altın sarısı gibi sıcak tonlara sahip paralel evren.
    - *Evren Değiştirme:* Her iki el de ekranın en üst kısımlarına (ilk %15''lik alana) kaldırıldığında iki evren arasında geçiş yapılır.
- **Derinlik Algısı (Z-Axis):** Elin ekrandaki büyüklüğü baz alınarak kameraya olan uzaklığı hesaplanır. Bu, 3 boyutlu bir his yaratarak sistemin tepkilerini zenginleştirir.
- **Bağımsız Motorlar:**
    - `art_engine.js`: Ekranda gördüğümüz görsel şöleni ve partikül fiziğini hesaplar.
    - `audio_engine.js`: El hareketlerine ve evren durumuna bağlı olarak dinamik ses sentezler.

## GitHub''dan İndirme ve Kurulum

Projede bir yapay zeka modeli (`hand_landmarker.task`) ve çeşitli modüler JavaScript dosyaları bulunduğu için, tarayıcıların güvenlik (CORS) kuralları gereği bu dosyaları yerel bir sunucu (Local Web Server) üzerinden çalıştırmalısınız.

İşte adım adım kurulum rehberi:

### Yöntem 1: Git Kullanarak (Önerilen)

1. **Repoyu Klonlayın:** Terminal veya komut satırınızı açıp aşağıdaki komutu çalıştırarak projeyi bilgisayarınıza indirin:

    ```
    git clone https://github.com/osmanbugrabolat/kozmik-toz-enstalasyon.git
    ```

2. **Proje Klasörüne Girin:**

    ```
    cd kozmik-toz-enstalasyon
    ```

### Yöntem 2: ZIP Olarak İndirme

1. Bu Github sayfasının sağ üst köşesindeki yeşil renkli **"Code"** butonuna tıklayın.
2. Açılan menüden **"Download ZIP"** seçeneğini seçerek dosyaları bilgisayarınıza indirin.
3. İnen ZIP dosyasını klasöre çıkartın (Extract).
4. Çıkardığınız klasörü VS Code veya tercih ettiğiniz başka bir kod editörü ile açın.

### Projeyi Çalıştırma

Projeyi tarayıcıda açmak için yerel sunucu başlatmanız gerekir. Bunun için iki kolay yol vardır:

- **Seçenek A (Node.js Yüklü İse):** Terminalinizde proje klasöründeyken şu komutu çalıştırın:

    ```
    npx serve .
    ```

- **Seçenek B (VS Code Kullanıyorsanız):** VS Code içerisinden eklentiler (Extensions) bölümüne gidip **"Live Server"** eklentisini kurun. Kurulum bittikten sonra `index.html` dosyasına sağ tıklayıp **"Open with Live Server"** seçeneğini seçin.

Tarayıcınız otomatik açılacak ve projeniz (genellikle `http://localhost:3000` veya `http://127.0.0.1:5500` adresinde) çalışmaya başlayacaktır.
Tarayıcının talep edeceği **Kamera İznini** onaylayın, sesi başlatmak için **ekrana bir kez tıklayın** ve ellerinizi kameraya göstererek evreni kontrol etmeye başlayın!

## Dosya Yapısı

- `index.html`: Projenin ana yapısı, video ve canvas bileşenleri.
- `style.css`: Arayüz tasarımı, tam ekran yerleşimleri.
- `script.js`: MediaPipe el algılama motorunun yüklenmesi, jest algılama (yumruk, çırpma vb.) ve ana kontrol döngüsü.
- `art_engine.js`: Canvas tabanlı interaktif çizim ve görsel simülasyon motoru.
- `audio_engine.js`: El hareketlerine ve derinliğe duyarlı çalışan dinamik ses motoru.
- `hand_landmarker.task`: MediaPipe tarafından kullanılan el takibi yapay zeka model dosyası.

## Kullanılan Teknolojiler

- **HTML5 Canvas API** (Görselleştirme için)
- **Web Audio API** (Ses sentezleme için)
- **MediaPipe Tasks Vision** (Yapay Zeka / El Takibi için)
- **Vanilla ES6+ JavaScript**', '', 'markdown', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('3503d03a-c809-548a-ac32-34aae38b882c', '259fe09b-c0a5-5faf-8b7b-7b68465b1ad1', 'file', 'Deneyimle', 'Experience', 'embed', 1, '/projects/kozmik-toz-enstalasyon/play', 'https://osmanbugrabolat.github.io/kozmik-toz-enstalasyon/', null, 'Kozmik Toz Enstalasyonu', '', 'play', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('bf357637-c09c-5ad4-b50d-0edccd88fb43', '12ec0a70-b90b-5dcd-9e16-5b9704ec4275', 'file', 'For more...', null, 'link', 6, null, 'https://github.com/osmanbugrabolat', null, '', '', 'github', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('866ffbc7-0aae-5cfb-b46e-d23302ba2f4e', '12ec0a70-b90b-5dcd-9e16-5b9704ec4275', 'file', 'Apart Yönetim Sistemi.md', null, 'markdown', 101, '/projects/1', null, null, '', '# Apart Yönetim Sistemi

2026 · Active

Comprehensive apartment management platform with real-time updates, tenant management, payment tracking, and automated reporting.

## Tech Stack

`Next.js` `TypeScript` `PostgreSQL` `Prisma` `Tailwind CSS`

## Links

- [Source Code](https://github.com/osmanbugrabolat)
- [Live Demo](http://localhost:3000)', 'markdown', false) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('070a8b5e-9caf-5cf2-b8a1-03fa923c8b31', '12ec0a70-b90b-5dcd-9e16-5b9704ec4275', 'file', 'Portfolyo AI.md', null, 'markdown', 102, '/projects/2', null, null, '', '# Portfolyo AI

2026 · Active

AI-powered portfolio website with a VS Code-inspired theme. Features intelligent content generation and interactive code-like navigation.

## Tech Stack

`Next.js` `TypeScript` `AI/ML` `Tailwind CSS`

## Links

- [Source Code](https://github.com/osmanbugrabolat)', 'markdown', false) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('21d37801-7a8d-5259-84b7-02fa1f6845c8', '12ec0a70-b90b-5dcd-9e16-5b9704ec4275', 'file', 'Fountain Detection AI.md', null, 'markdown', 103, '/projects/3', null, null, '', '# Fountain Detection AI

2025 · Completed

Fine-tuned YOLOv8 & YOLOv11 model for detecting historical Ottoman fountains (hayrat çeşme) in images with high accuracy.

## Tech Stack

`Python` `YOLOv11` `Ultralytics` `OpenCV` `PyTorch`

## Links

- [Source Code](https://github.com/osmanbugrabolat)', 'markdown', false) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('5e519983-91ba-5e25-885a-9ea71221c5dd', '12ec0a70-b90b-5dcd-9e16-5b9704ec4275', 'file', 'Web Scraper & Dataset Builder.md', null, 'markdown', 104, '/projects/4', null, null, '', '# Web Scraper & Dataset Builder

2025 · Completed

Automated image scraping tool for building custom computer vision datasets from Google Images search results.

## Tech Stack

`Python` `Selenium` `BeautifulSoup` `Requests`

## Links

- [Source Code](https://github.com/osmanbugrabolat)', 'markdown', false) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, sort_order, icon, show_in_explorer) values ('69079713-4708-5fb1-9e39-947bd0405284', null, 'folder', 'articles', 2, 'book', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('c5fc124e-8b8b-5e11-a9f8-0d418afe0bca', '69079713-4708-5fb1-9e39-947bd0405284', 'file', 'Altyapıyı Unutun, Koda Odaklanın: FaaS', null, 'link', 0, null, 'https://medium.com/@osmanbugrabolat/altyap%C4%B1y%C4%B1-unutun-koda-odaklan%C4%B1n-function-as-a-service-faas-58978592d739', null, '', '', 'medium', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('6621e2f6-a695-56ee-973f-4d66c7f63dbf', '69079713-4708-5fb1-9e39-947bd0405284', 'file', 'Açık Kaynak vs Açık Ağırlık', null, 'link', 1, null, 'https://medium.com/@osmanbugrabolat/yapay-zeka-d%C3%BCnyas%C4%B1nda-kavram-karma%C5%9Fas%C4%B1-open-source-model-vs-open-weight-model-32ccccd2f0f5', null, '', '', 'medium', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('d3d49547-07e6-5a4a-a6f3-ba5d8b3de8b0', '69079713-4708-5fb1-9e39-947bd0405284', 'file', 'Yapay Zeka İletişiminin Sessiz Devrimi: MCP', null, 'link', 2, null, 'https://medium.com/@osmanbugrabolat/yapay-zeka-i%CC%87leti%C5%9Fiminin-sessiz-devrimi-model-context-protocol-83ca52c1a82c', null, '', '', 'medium', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('e163353c-cf03-5593-bd3f-05b8aaeee658', '69079713-4708-5fb1-9e39-947bd0405284', 'file', 'Yeni Geleceğin Başlangıcı: Yapay Zeka', null, 'link', 3, null, 'https://medium.com/@osmanbugrabolat/yeni-gelece%C4%9Fin-ba%C5%9Flang%C4%B1c%C4%B1-yapay-zeka-9313cb13e31f', null, '', '', 'medium', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('1b68d2ea-b63d-51ac-8a09-de263d186e41', '69079713-4708-5fb1-9e39-947bd0405284', 'file', 'For more...', null, 'link', 4, null, 'https://medium.com/@osmanbugrabolat', null, '', '', 'medium', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('eddb7709-14f7-56bd-9b49-a8ce6d658bc3', '69079713-4708-5fb1-9e39-947bd0405284', 'file', 'articles.md', null, 'markdown', 99, '/articles', null, null, '', '# Articles

I enjoy sharing what I learn and writing about my journey in tech. Here are some of my recent articles.

## [Building a VS Code Theme Portfolio with Next.js](#)

June 2026 • 5 min read

An in-depth look at how I built this portfolio website to mimic the VS Code interface, using Next.js, Tailwind CSS, and custom UI components.

## [Fine-tuning YOLO Models for Custom Object Detection](#)

May 2026 • 8 min read

A step-by-step guide to fine-tuning YOLOv11 and YOLOv8 on custom datasets, focusing on historical fountains detection.', 'markdown', false) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, sort_order, icon, show_in_explorer) values ('29b22436-2747-5554-8354-8ca57a2a13aa', null, 'folder', 'certificates', 3, 'certificate', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('07587d2e-7a01-5751-a35c-31e9e21eb53c', '29b22436-2747-5554-8354-8ca57a2a13aa', 'file', 'SQL & Oracle Database', null, 'image', 0, '/certificates/oracle', null, '/certificates/oracle_cert.jpg', '', '', 'image', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('dc28d025-038f-50bb-89f6-aa243559cfb8', '29b22436-2747-5554-8354-8ca57a2a13aa', 'file', 'Python & Tensorflow', null, 'image', 1, '/certificates/python', null, '/certificates/python_tensorflow.jpg', '', '', 'image', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('aae23d22-260e-501d-b413-b9cc07b3e152', '29b22436-2747-5554-8354-8ca57a2a13aa', 'file', 'R Programming', null, 'image', 2, '/certificates/r-lang', null, '/certificates/r_programming.jpg', '', '', 'image', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('1178ec62-e8f1-58ad-a752-755d0db4da02', '29b22436-2747-5554-8354-8ca57a2a13aa', 'file', 'Huawei HCCDA-AI', null, 'image', 3, '/certificates/hwend-177820', null, '/certificates/HWEND_177820.png', '', '', 'image', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('6be4e85b-2d17-5b6e-b238-89ba11d05850', '29b22436-2747-5554-8354-8ca57a2a13aa', 'file', 'Huawei HCCDP-AI', null, 'image', 4, '/certificates/hwend-721526', null, '/certificates/HWEND_721526.png', '', '', 'image', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('379d97c0-7c15-541f-956f-efea524f058f', '29b22436-2747-5554-8354-8ca57a2a13aa', 'file', 'Huawei HCCDP-Cloud Migration', null, 'image', 5, '/certificates/hwend-036679', null, '/certificates/HWEND_036679.png', '', '', 'image', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('e45e29d8-17c4-5feb-88f7-e0ed901de855', '29b22436-2747-5554-8354-8ca57a2a13aa', 'file', 'Huawei HCCDP-Solution Architectures', null, 'image', 6, '/certificates/hwend-580148', null, '/certificates/HWEND_580148.png', '', '', 'image', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('f2e5a592-a170-5bd1-ad92-8ffa79e88569', '29b22436-2747-5554-8354-8ca57a2a13aa', 'file', 'Huawei HCCDA-Cloud Native', null, 'image', 7, '/certificates/hwend-690969', null, '/certificates/HWEND_690969.png', '', '', 'image', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('d3c3a396-0819-5fab-8f4d-b43e4dab6762', '29b22436-2747-5554-8354-8ca57a2a13aa', 'file', 'Huawei HCCDA-Tech Essentials', null, 'image', 8, '/certificates/hwend-727737', null, '/certificates/HWEND_727737.png', '', '', 'image', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, sort_order, icon, show_in_explorer) values ('40506c79-7c4f-5d86-820b-2faf76736766', null, 'folder', 'contact', 4, 'mail', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('1891ffa8-203a-5631-b9e9-8b1089584ff9', '40506c79-7c4f-5d86-820b-2faf76736766', 'file', 'LinkedIn', null, 'link', 0, null, 'https://linkedin.com/in/osmanbugrabolat', null, '', '', 'linkedin', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('c64af12c-f1f2-5a0c-ba99-d4a3407bcfab', '40506c79-7c4f-5d86-820b-2faf76736766', 'file', 'GitHub', null, 'link', 1, null, 'https://github.com/osmanbugrabolat', null, '', '', 'github', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('7ea8f40f-3ba0-5b1f-b049-8a2e460f80a5', '40506c79-7c4f-5d86-820b-2faf76736766', 'file', 'Medium', null, 'link', 2, null, 'https://medium.com/@osmanbugrabolat', null, '', '', 'medium', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('2a061be8-1ee3-5fad-a21a-047c75e87fd7', '40506c79-7c4f-5d86-820b-2faf76736766', 'file', 'E-Mail', null, 'link', 3, null, 'mailto:contact@bugrabolat.dev', null, '', '', 'email', true) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('a0b104dc-61d0-56d0-8fe8-af7be79fec95', '40506c79-7c4f-5d86-820b-2faf76736766', 'file', 'contact.md', null, 'markdown', 99, '/contact', null, null, '', '# Contact & Connect

I''m always open to discussing new projects, creative ideas, or opportunities to be part of your visions.

## Get in Touch

The best way to reach me is via email. I usually respond within 24-48 hours.

{{contact-details}}

## Social Profiles

{{social-links}}

> *"Code is like humor. When you have to explain it, it’s bad."* – Cory House', 'markdown', false) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('48257011-566e-50d1-bd13-a683d2deef5b', null, 'file', 'cv.pdf', null, 'pdf', 10, '/cv', null, '/cv.pdf', '', '', 'pdf', false) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('14ab6162-3ebc-5ac1-a1a6-81528882b35a', null, 'file', 'experience.ts', null, 'experience', 11, '/experience', null, null, '', '', 'typescript', false) on conflict (id) do nothing;
insert into public.explorer_nodes (id, parent_id, kind, name, name_en, file_type, sort_order, route, url, asset_url, content_tr, content_en, icon, show_in_explorer) values ('0ab97883-e131-5aae-a152-630fd6b39cd5', null, 'file', 'skills.ts', null, 'skills', 12, '/skills', null, null, '', '', 'typescript', false) on conflict (id) do nothing;

insert into public.skill_categories (id, key, label_tr, label_en, type_name, sort_order) values ('986e24f9-8f70-5284-ad34-c7ba92b9f008', 'ai_ml', 'AI-ML', 'AI-ML', 'MLTool[]', 0) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('6168bdaa-2101-5865-ad8f-1383465a86f3', '986e24f9-8f70-5284-ad34-c7ba92b9f008', 'Ultralytics YOLO', 75, 'ultralytics', 0) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('45696f48-5c04-52c8-839b-753aa089f011', '986e24f9-8f70-5284-ad34-c7ba92b9f008', 'MediaPipe', 75, 'mediapipe', 1) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('eee5729d-fdc7-5dd5-9843-a175eab010d3', '986e24f9-8f70-5284-ad34-c7ba92b9f008', 'OpenCV', 70, 'opencv', 2) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('ba6dcb3f-8191-500b-b778-cd4f35c1a5f6', '986e24f9-8f70-5284-ad34-c7ba92b9f008', 'TensorFlow', 70, 'tensorflow', 3) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('98c99407-ba9f-5160-b97d-818f8d7eca4f', '986e24f9-8f70-5284-ad34-c7ba92b9f008', 'PyTorch', 65, 'pytorch', 4) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('735483fd-5c95-5a48-b683-7240c2d30259', '986e24f9-8f70-5284-ad34-c7ba92b9f008', 'Scikit-learn', 60, 'scikitlearn', 5) on conflict (id) do nothing;
insert into public.skill_categories (id, key, label_tr, label_en, type_name, sort_order) values ('f355756c-37c4-5f5e-891f-8c944f972f4b', 'cloud', 'Bulut Platformları', 'Cloud Platforms', 'CloudPlatform[]', 1) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('b3e43db0-5f3b-53d5-b817-430db2138b75', 'f355756c-37c4-5f5e-891f-8c944f972f4b', 'Huawei Cloud', 70, 'huawei', 0) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('5085e014-719b-53ca-b308-19a02fe9c0e1', 'f355756c-37c4-5f5e-891f-8c944f972f4b', 'GCP', 60, 'googlecloud', 1) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('83d0cb76-6544-54b2-aa36-fb91bf42dad1', 'f355756c-37c4-5f5e-891f-8c944f972f4b', 'AWS', 55, 'aws', 2) on conflict (id) do nothing;
insert into public.skill_categories (id, key, label_tr, label_en, type_name, sort_order) values ('83c8c932-d236-5be3-8e13-be162d93b348', 'frontend', 'Frontend', 'Frontend', 'Framework[]', 2) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('7887cdec-462c-563f-9af3-e9a0fbe1d180', '83c8c932-d236-5be3-8e13-be162d93b348', 'Next.js', 90, 'nextjs', 0) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('8fd68e5b-9099-595a-81d0-d840c3c3a9da', '83c8c932-d236-5be3-8e13-be162d93b348', 'React', 85, 'react', 1) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('a10607f0-ae24-559e-bccd-31f8022fdea7', '83c8c932-d236-5be3-8e13-be162d93b348', 'React Native', 80, 'react', 2) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('c3cfdb3e-d0cc-5d22-a2cb-9b36e5e10124', '83c8c932-d236-5be3-8e13-be162d93b348', 'Flutter', 70, 'flutter', 3) on conflict (id) do nothing;
insert into public.skill_categories (id, key, label_tr, label_en, type_name, sort_order) values ('17415bc4-ff37-521a-b140-96da0e840567', 'backend', 'Backend', 'Backend', 'Framework[]', 3) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('330b8171-3797-53ed-9271-a764d84b3c8e', '17415bc4-ff37-521a-b140-96da0e840567', 'Python FastAPI', 75, 'fastapi', 0) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('d4a9e4cc-207e-51bd-9e60-b56aec9e5c5b', '17415bc4-ff37-521a-b140-96da0e840567', 'Node.js', 70, 'nodejs', 1) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('885457fb-f9e5-5910-a367-c6e1b81c5d72', '17415bc4-ff37-521a-b140-96da0e840567', 'Prisma ORM', 60, 'prisma', 2) on conflict (id) do nothing;
insert into public.skill_categories (id, key, label_tr, label_en, type_name, sort_order) values ('1e88c297-1cdd-560a-9646-1dcacb57c506', 'databases', 'Veritabanları', 'Databases', 'Database[]', 4) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('a59905d5-b7c3-557f-969d-75e505f6d117', '1e88c297-1cdd-560a-9646-1dcacb57c506', 'PostgreSQL', 75, 'postgresql', 0) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('b77262ee-5af3-5e12-8da3-b0b9c5a6ee17', '1e88c297-1cdd-560a-9646-1dcacb57c506', 'MSSQL', 65, 'mssql', 1) on conflict (id) do nothing;
insert into public.skill_categories (id, key, label_tr, label_en, type_name, sort_order) values ('278d09ec-a924-5484-8953-41adaa5fb0ed', 'tools', 'Araçlar ve Ortamlar', 'Tools & Environments', 'Tool[]', 5) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('bfcb6e0b-c274-532f-be6a-053136306880', '278d09ec-a924-5484-8953-41adaa5fb0ed', 'VS Code', 99, 'vscode', 0) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('48efa808-84d1-5fc7-b340-4c7590ed0a87', '278d09ec-a924-5484-8953-41adaa5fb0ed', 'Git & GitHub', 80, 'github', 1) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('d4f6b802-e5ea-57f0-acbc-98e4fe7d803a', '278d09ec-a924-5484-8953-41adaa5fb0ed', 'Docker', 65, 'docker', 2) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('a44aaf02-209c-5533-a5cf-d74d1d49f40a', '278d09ec-a924-5484-8953-41adaa5fb0ed', 'Figma', 60, 'figma', 3) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('9cf04923-96fb-53f2-a1e0-d40aafc215d8', '278d09ec-a924-5484-8953-41adaa5fb0ed', 'Linux', 75, 'linux', 4) on conflict (id) do nothing;
insert into public.skill_categories (id, key, label_tr, label_en, type_name, sort_order) values ('286cf3f5-2143-5522-83ac-e2c8816b0450', 'ai_tools', 'Yapay Zeka Araçları', 'AI Tools', 'AITool[]', 6) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('4d7a52ed-0ae9-5a79-98af-349888661657', '286cf3f5-2143-5522-83ac-e2c8816b0450', 'Claude', 80, 'claude', 0) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('1fdb412c-aa15-5ada-bd97-38148c06924f', '286cf3f5-2143-5522-83ac-e2c8816b0450', 'Cursor', 70, 'cursor', 1) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('421af96d-f90e-5235-bb35-db3e42e53046', '286cf3f5-2143-5522-83ac-e2c8816b0450', 'Gemini', 70, 'gemini', 2) on conflict (id) do nothing;
insert into public.skill_categories (id, key, label_tr, label_en, type_name, sort_order) values ('986ec933-379d-525f-9252-bd6a969ca52b', 'project_management', 'Proje Yönetimi', 'Project Management', 'PMTool[]', 7) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('0c0847f5-6e30-5bd4-9dd0-e99478994b33', '986ec933-379d-525f-9252-bd6a969ca52b', 'Slack', 85, 'slack', 0) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('74e0c00f-a08e-5432-86a7-62cbc074c839', '986ec933-379d-525f-9252-bd6a969ca52b', 'Trello', 80, 'trello', 1) on conflict (id) do nothing;
insert into public.skills (id, category_id, name, level, icon, sort_order) values ('9264012c-73fd-5957-97db-c294ba1be9df', '986ec933-379d-525f-9252-bd6a969ca52b', 'Jira', 70, 'jira', 2) on conflict (id) do nothing;

insert into public.experiences (id, company, position_tr, position_en, duration_tr, duration_en, location_tr, location_en, description_tr, description_en, highlights_tr, highlights_en, tech, sort_order) values ('65755aca-a88f-5d90-89d9-2096cdc78f76', 'Freelance', '', 'Full Stack Developer', '2024 – Günümüz', '2024 – Present', 'Uzaktan', 'Remote', '', 'Designing and developing custom web applications for clients. Specialized in Next.js, TypeScript, and database architecture.', array[]::text[], array['Built Apart Yönetim Sistemi for property management', 'Developed AI-powered portfolio websites', 'Delivered 5+ projects on time and within scope']::text[], array['Next.js', 'TypeScript', 'PostgreSQL', 'Prisma', 'Tailwind CSS']::text[], 0) on conflict (id) do nothing;
insert into public.experiences (id, company, position_tr, position_en, duration_tr, duration_en, location_tr, location_en, description_tr, description_en, highlights_tr, highlights_en, tech, sort_order) values ('750b46d1-bd96-5dc3-a95f-568605e45234', 'Self-Directed Learning', '', 'AI/ML Engineer (Learning)', '2025 – Günümüz', '2025 – Present', 'Türkiye', 'Turkey', '', 'Deep diving into computer vision and machine learning. Working on fine-tuning YOLO models for object detection tasks.', array[]::text[], array['Fine-tuned YOLOv8 & YOLOv11 for fountain detection', 'Built custom datasets from web scraped images', 'Achieved 85%+ mAP on custom dataset']::text[], array['Python', 'PyTorch', 'Ultralytics', 'OpenCV', 'NumPy']::text[], 1) on conflict (id) do nothing;

commit;
